name:                flatscraper
version:             0.1.0.0
license:             GPL-3
author:              "Marcin Moskal"
maintainer:          "mmos@memleak.pl"
copyright:           "2019 Marcin Moskal"

extra-source-files:
- README.md

description:         Please see the README at <https://gitlab.memleak.pl/mmos/flatscraper#readme>

dependencies:
- base >= 4.7 && < 5
- scalpel >= 0.5
- text
- feed
- persistent
- persistent-template
- persistent-sqlite
- time

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  flatscraper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flatscraper
