name:                flatscraper
version:             0.2.0.0
license:             GPL-3
author:              "Marcin Moskal"
maintainer:          "mmos@memleak.pl"
copyright:           "2019-2025 Marcin Moskal"

extra-source-files:
- README.md

description:         Please see the README at <https://gitlab.memleak.pl/mmos/flatscraper#readme>

dependencies:
- base >= 4.10 && < 5
- aeson
- aeson-casing
- aeson-pretty
- blaze-html
- bytestring
- case-insensitive
- containers
- either
- feed
- HaskellNet
- HaskellNet-SSL
- http-client
- http-client-tls
- lens
- lens-aeson
- persistent
- persistent-template
- persistent-sqlite
- process
- process-extras
- regex
- regex-tdfa
- scalpel >= 0.6 && <0.7
- tagsoup
- text
- text-icu
- unliftio-core
- time
- vector

library:
  source-dirs: src
  ghc-options:
    - -Wall

default-extensions:
  - OverloadedStrings

executables:
  new-cli:
    main:                Main.hs
    source-dirs:         new-cli
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flatscraper

  flatscraper-scrape:
    main:                Main.hs
    source-dirs:         cli/scrape
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flatscraper

  flatscraper-gen-feed:
    main:                Main.hs
    source-dirs:         cli/gen-feed
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flatscraper

  flatscraper-send-digest:
    main:                Main.hs
    source-dirs:         cli/send-digest
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flatscraper

  flatscraper-process-location:
    main:                Main.hs
    source-dirs:         cli/process-location
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flatscraper

tests:
  spec:
    source-dirs: test
    main: Test.hs
    dependencies:
    - hspec
    - flatscraper
