name:                flatscraper
version:             0.1.0.0
license:             GPL-3
author:              "Marcin Moskal"
maintainer:          "mmos@memleak.pl"
copyright:           "2019 Marcin Moskal"

extra-source-files:
- README.md

description:         Please see the README at <https://gitlab.memleak.pl/mmos/flatscraper#readme>

dependencies:
- base >= 4.10 && < 5
- feed
- persistent
- persistent-template
- persistent-sqlite
- scalpel >= 0.6 && <0.7
- text
- time

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  flatscraper:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    dependencies:
    - flatscraper
